openapi: 3.0.0
info:
  title: DICOM Web UPS-RS API
  version: 1.0.0
  description: API specification for DICOM Web UPS-RS (Unified Procedure Step - RESTful Services)

paths:
  /workitems:
    get:
      operationId: listWorkitems
      summary: Search for Workitems
      description: This resource allows searching for UPS Workitems based on specified parameters.
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/FuzzyMatching'
        - $ref: '#/components/parameters/IncludeField'
        - $ref: '#/components/parameters/WorklistLabel'
        - $ref: '#/components/parameters/ProcedureStepState'
        - $ref: '#/components/parameters/ScheduledProcedureStepStartDateTime'
        - $ref: '#/components/parameters/ScheduledStationName'
        - $ref: '#/components/parameters/ScheduledStationAETitle'
      responses:
        '200':
          description: Successful response
          content:
            application/dicom+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workitem'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/DefaultError'
    post:
      operationId: CreateWorkitem
      summary: Create a Workitem
      description: Creates a new UPS Workitem
      requestBody:
        required: true
        content:
          application/dicom+json:
            schema:
              $ref: '#/components/schemas/Workitem'
      responses:
        '201':
          description: Workitem created successfully
          headers:
            Location:
              schema:
                type: string
                maxLength: 10240
                pattern: ^(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$
              description: URI of the created Workitem
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'

        default:
          $ref: '#/components/responses/DefaultError'

  /workitems/{workitemUID}:
    get:
      operationId: RetrieveWorkitem
      summary: Retrieve a Workitem
      description: Retrieves a specific UPS Workitem
      parameters:
        - $ref: '#/components/parameters/WorkitemUID'
      responses:
        '200':
          description: Successful response
          content:
            application/dicom+json:
              schema:
                $ref: '#/components/schemas/Workitem'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/DefaultError'

    post:
      operationId: UpdateWorkitem
      summary: Update a Workitem
      description: Updates a specific UPS Workitem
      parameters:
        - $ref: '#/components/parameters/WorkitemUID'
      requestBody:
        required: true
        content:
          application/dicom+json:
            schema:
              $ref: '#/components/schemas/Workitem'
      responses:
        '200':
          description: Workitem updated successfully
          content:
            application/dicom+json:
              schema:
                $ref: '#/components/schemas/Workitem'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/DefaultError'

  /workitems/{workitemUID}/state:
    put:
      operationId: ChangeWorkitemState
      summary: Change Workitem State
      description: Changes the state of a specific UPS Workitem
      parameters:
        - $ref: '#/components/parameters/WorkitemUID'
      requestBody:
        required: true
        content:
          application/dicom+json:
            schema:
              type: object
              additionalProperties: false
              required:
                - ProcedureStepState
              properties:
                ProcedureStepState:
                  type: string
                  enum: [IN PROGRESS, COMPLETED, CANCELED]
      responses:
        '200':
          description: Workitem state changed successfully
          content:
            application/dicom+json:
              schema:
                $ref: '#/components/schemas/Workitem'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/DefaultError'

  /workitems/{workitemUID}/cancelrequest:
    post:
      operationId: CancelWorkitem
      summary: Request Cancellation of a Workitem
      description: Requests cancellation of a specific UPS Workitem
      parameters:
        - $ref: '#/components/parameters/WorkitemUID'
      requestBody:
        required: true
        content:
          application/dicom+json:
            schema:
              type: object
              additionalProperties: false
              required:
                - ReasonForCancellation
              properties:
                ReasonForCancellation:
                  type: string
                  maxLength: 10240
                  pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
      responses:
        '202':
          description: Cancellation request accepted
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/DefaultError'

components:
  parameters:
    WorkitemUID:
      name: workitemUID
      in: path
      required: true
      description: Unique identifier of the Workitem
      schema:
        type: string
        pattern: ^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*$
        maxLength: 64
    Limit:
      name: limit
      in: query
      description: Maximum number of results to return
      schema:
        type: integer
        maximum: 10000
        minimum: 1
    Offset:
      name: offset
      in: query
      description: Number of results to skip before returning matches
      schema:
        type: integer
        maximum: 10000
        minimum: 1
    FuzzyMatching:
      name: fuzzymatching
      in: query
      description: Whether fuzzy semantic matching should be performed
      schema:
        type: boolean
    IncludeField:
      name: includefield
      in: query
      description: Fields to include in the response
      schema:
        type: array
        items:
          type: string
          pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
          maxLength: 64
    WorklistLabel:
      name: WorklistLabel
      in: query
      description: Label of the Worklist to which the Workitem belongs
      schema:
        type: string
        maxLength: 64
        pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
    ProcedureStepState:
      name: ProcedureStepState
      in: query
      description: Current state of the Procedure Step
      schema:
        type: string
        enum: [SCHEDULED, IN PROGRESS, COMPLETED, CANCELED]
    ScheduledProcedureStepStartDateTime:
      name: ScheduledProcedureStepStartDateTime
      in: query
      description: Scheduled start date and time for the Procedure Step
      schema:
        type: string
        format: date-time
    ScheduledStationName:
      name: ScheduledStationName
      in: query
      description: Name of the scheduled station
      schema:
        type: string
        maxLength: 16
        pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
    ScheduledStationAETitle:
      name: ScheduledStationAETitle
      in: query
      description: Application Entity Title of the scheduled station
      schema:
        type: string
        maxLength: 16
        pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                maxLength: 64
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                example: "Resource not found"
              resourceId:
                type: string
                maxLength: 1024
                example: "Resource ID not found"
    NotAcceptable:
      description: Not Acceptable
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                maxLength: 1024
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                example: "The request is not supported"
    TooManyRequests:
      description: Too many requests, please try again later.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                maxLength: 1024
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                example: "Rate limit exceeded"
              retryAfter:
                type: integer
                description: Number of seconds to wait before retrying
                example: 60
      headers:
        Retry-After:
          description: Number of seconds to wait before retrying
          schema:
            type: integer
    DefaultError:
      description: An unexpected error occurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                maxLength: 1024
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                example: "An unexpected error occurred"
              errorCode:
                type: string
                maxLength: 64
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                example: "INTERNAL_SERVER_ERROR"
    Conflict:
      description: The request could not be completed due to a conflict with the current state of the target resource
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unable to update resource due to a conflict"
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                maxLength: 1024
              details:
                type: object
                example:
                  conflictingField: "workitemUID"
                  currentValue: "workitemUID"
                  attemptedValue: "workitemUID"
              conflictType:
                type: string
                enum: [CONCURRENT_MODIFICATION, UNIQUE_CONSTRAINT, STATE_CONFLICT, DEPENDENCY_CONFLICT]
                example: "UNIQUE_CONSTRAINT"

  schemas:
    Workitem:
      type: object
      additionalProperties: true
      required:
        - WorkitemUID
        - ProcedureStepState
        - ScheduledProcedureStepStartDateTime
        - ScheduledWorkitemCodeSequence
        - InputInformationSequence
      properties:
        WorkitemUID:
          type: string
          pattern: ^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*$
          maxLength: 64
        ProcedureStepState:
          type: string
          enum: [SCHEDULED, IN PROGRESS, COMPLETED, CANCELED]
        ScheduledProcedureStepStartDateTime:
          type: string
          maxLength: 1024
          format: date-time
        ScheduledWorkitemCodeSequence:
          type: object
          additionalProperties: true
          properties:
            CodeValue:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodingSchemeDesignator:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodeMeaning:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 64
        InputInformationSequence:
          type: array
          items:
            type: object
            additionalProperties: true
            properties:
              StudyInstanceUID:
                type: string
                pattern: ^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*$
                maxLength: 64
              SeriesInstanceUID:
                type: string
                pattern: ^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*$
                maxLength: 64
        ScheduledStationNameCodeSequence:
          type: object
          additionalProperties: true
          properties:
            CodeValue:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodingSchemeDesignator:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodeMeaning:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 64
        ScheduledStationClassCodeSequence:
          type: object
          additionalProperties: false
          properties:
            CodeValue:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodingSchemeDesignator:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodeMeaning:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 64
        ScheduledStationGeographicLocationCodeSequence:
          type: object
          additionalProperties: true
          properties:
            CodeValue:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodingSchemeDesignator:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodeMeaning:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 64
        ScheduledHumanPerformersSequence:
          type: array
          items:
            type: object
            additionalProperties: false
            properties:
              HumanPerformerCodeSequence:
                type: object
                additionalProperties: true
                properties:
                  CodeValue:
                    type: string
                    pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                    maxLength: 16
                  CodingSchemeDesignator:
                    type: string
                    pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                    maxLength: 16
                  CodeMeaning:
                    type: string
                    pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                    maxLength: 64
              HumanPerformerName:
                type: string
                pattern: ^(?:([^\\^=]*(?:\^[^\\^=]*){0,4})(?:=([^\\^=]*(?:\^[^\\^=]*){0,4}))?(?:=([^\\^=]*(?:\^[^\\^=]*){0,4}))?)?$
                maxLength: 196
        ScheduledProcedureStepDescription:
          type: string
          maxLength: 64
          pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
        ScheduledProtocolCodeSequence:
          type: object
          properties:
            CodeValue:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodingSchemeDesignator:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 16
            CodeMeaning:
              type: string
              pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
              maxLength: 64
        ReferencedRequestSequence:
          type: array
          items:
            type: object
            properties:
              StudyInstanceUID:
                type: string
                pattern: ^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*$
                maxLength: 64
              AccessionNumber:
                type: string
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                maxLength: 16
              RequestedProcedureID:
                type: string
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                maxLength: 16
              RequestedProcedureDescription:
                type: string
                pattern: ^[\x20-\x7E\x0A\x0C\x0D\x09]*$
                maxLength: 64
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

    basicAuth:
      type: http
      scheme: basic

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read:data: Read access to data
            write:data: Write access to data

    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration

    jwtBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT



security:
  - apiKey: []
  - basicAuth: []
  - bearerAuth: []
  - oauth2: ['read:data', 'write:data']
  - openIdConnect: []
  - jwtBearer: []
